# All Pipeline configuration
---
# all paths should be relevant to pipeline module
# all paths should use '/' as folders separator

extract:
  type: csv
  params:
    path: ../../data/input/Sales data.csv
    columns:
      - order_id
      - customer_id
      - product_id
      - quantity
      - price
      - order_date

transform:
  users_api_url: https://jsonplaceholder.typicode.com/users
  weather_api_url: https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid={API_KEY}


load:
  type: lite_db
  params:
    path_to_db: ../../data/output/DB.db
    path_to_creation_file: ../../configs/schema_creation.sql
